export enum PokemonType {
    NORMAL = "Normal",
    FIRE = "Fire",
    WATER = "Water",
    ELECTRIC = "Electric",
    GRASS = "Grass",
    ICE = "Ice",
    FIGHTING = "Fighting",
    POISON = "Poison",
    GROUND = "Ground",
    FLYING = "Flying",
    PSYCHIC = "Psychic",
    BUG = "Bug",
    ROCK = "Rock",
    GHOST = "Ghost",
    DRAGON = "Dragon",
    DARK = "Dark",
    STEEL = "Steel",
    FAIRY = "Fairy",
}

export const PokemonTypeIconMap: Map<string, string> = new Map<string, string>([
    [PokemonType.NORMAL, "assets/types/normal.svg"],
    [PokemonType.FIRE, "assets/types/fire.svg"],
    [PokemonType.WATER, "assets/types/water.svg"],
    [PokemonType.ELECTRIC, "assets/types/electric.svg"],
    [PokemonType.GRASS, "assets/types/grass.svg"],
    [PokemonType.ICE, "assets/types/ice.svg"],
    [PokemonType.FIGHTING, "assets/types/fighting.svg"],
    [PokemonType.POISON, "assets/types/poison.svg"],
    [PokemonType.GROUND, "assets/types/ground.svg"],
    [PokemonType.FLYING, "assets/types/flying.svg"],
    [PokemonType.PSYCHIC, "assets/types/psychic.svg"],
    [PokemonType.BUG, "assets/types/bug.svg"],
    [PokemonType.ROCK, "assets/types/rock.svg"],
    [PokemonType.GHOST, "assets/types/ghost.svg"],
    [PokemonType.DRAGON, "assets/types/dragon.svg"],
    [PokemonType.DARK, "assets/types/dark.svg"],
    [PokemonType.STEEL, "assets/types/steel.svg"],
    [PokemonType.FAIRY, "assets/types/fairy.svg"],
]);
